---
# -*- coding: utf-8 -*-
image: quay.io/ansible/molecule:latest
services:
  - docker:dind

before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

stages:
  - lint
  - test

molecule-lint:
  stage: lint
  script:
    - molecule lint

molecule-test:
  stage: test
  script:
    - molecule test
