---
# -*- coding: utf-8 -*-
image: quay.io/ansible/molecule:latest
services:
  - docker:dind

before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

stages:
  - lint

ansible-lint-pip:
  stage: lint
  script:
    - ansible-lint tests/test-pip.yml

ansible-lint-docker:
  stage: lint
  script:
    - ansible-lint tests/test-docker.yml

molecule-lint:
  stage: lint
  script:
    - molecule lint
