---
language: python
services: docker

env:
  global:
    - ROLE_NAME: matrix_ansible_synapse
  matrix:
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule docker

jobs:
  include:
    - stage: pip
      script: molecule test
    - stage: docker
      script: molecule test --scenario-name docker
